### PR TITLE
Fix unused hide var

### LINKED ISSUE #5: hideMessage() not used
Hi !
The `OPENCOLLECTIVE_HIDE` variable doesn't have any effect. In production or integration environnements, the message should not appear and no HTTP request should be performed.

If I understand correctly, the [init function](https://github.com/nuxt/opencollective/blob/4673fa06858ffb04e0b9c065497577edbc8f0fd0/src/init.js#L6) should just return when the `hide` variable is set.

### PR DESCRIPTION
**Pull request by nojhamster**
Fixes #5

### CODE REVIEW

**Comment by manniL** [comment]
Re-opening for circle trigger

**Comment by manniL** [comment]
@nojhamster 	Looking good so far. Could you add a test that covers the change? :relaxed:

**Comment by nojhamster** [comment]
@manniL Added a test to cover the change. I added some hooks in order to reset fetch-mock history, so that we can assert that fetch is not called when not needed.

**Comment by manniL** [comment]
@nojhamster 	many thanks!

**Pull request merged**
